### ISSUE TITLE
[BUG] plugging a NTFS drive breaks the linux os plugin

### ISSUE THREAD

**Issue by marcogozzi** [eclipse-fog05/plugin-os-linux#6]
**Describe the bug**
Plugging a NTFS-formatted SATA drive previously used in a Windows system in a node makes the plugin fail

**To Reproduce**
1. Install fog05 without the drive
2. Shut down the node and plug the drive
3. Boot the node and start the plugin
4. The plugin fails to start

**Expected behavior**
Linux OS Plugin should start normally

**Log**
Running `journalctl -u fos_linux.service`
```
feb 27 15:52:29 marco systemd[1]: Started fos_linux.service.
feb 27 15:52:29 marco fos_linux[10679]: ARGS ['/etc/fos/plugins/plugin-os-linux/linux_plugin', '/etc/fos/plugins/plugin-os-linux/linux_plugin.json']
feb 27 15:52:29 marco fos_linux[10679]: [2020-02-27 15:52:29,769] - [INFO] > < __init__() >  Hello from GNU\Linux Plugin
feb 27 15:52:29 marco fos_linux[10679]: [2020-02-27 15:52:29,796] - [INFO] > < __init__() >  Running on ubuntu
feb 27 15:52:29 marco fos_linux[10679]: [2020-02-27 15:52:29,797] - [INFO] > < __init__() >  Package manger apt loaded!
feb 27 15:52:29 marco sudo[10717]:      fos : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/etc/fos/plugins/plugin-os-linux/scripts/default_gw.sh
feb 27 15:52:29 marco sudo[10717]: pam_unix(sudo:session): session opened for user root by (uid=0)
feb 27 15:52:29 marco sudo[10717]: pam_unix(sudo:session): session closed for user root
feb 27 15:52:29 marco fos_linux[10679]: [2020-02-27 15:52:29,802] - [INFO] > < get_intf_type() > OS Plugin Interface lo is of type loopback
feb 27 15:52:29 marco fos_linux[10679]: [2020-02-27 15:52:29,803] - [INFO] > < get_intf_type() > OS Plugin Interface enp34s0 is of type ethernet
feb 27 15:52:29 marco fos_linux[10679]: [2020-02-27 15:52:29,803] - [INFO] > < __init__() > [ INIT ] Populating Global Actual Store with data from OS Plugin
feb 27 15:52:29 marco fos_linux[10679]: Traceback (most recent call last):
feb 27 15:52:29 marco fos_linux[10679]:   File "/etc/fos/plugins/plugin-os-linux/linux_plugin", line 1007, in <module>
feb 27 15:52:29 marco fos_linux[10679]:     'uuid'), manifest)
feb 27 15:52:29 marco fos_linux[10679]:   File "/etc/fos/plugins/plugin-os-linux/linux_plugin", line 98, in __init__
feb 27 15:52:29 marco fos_linux[10679]:     self.__populate_node_information()
feb 27 15:52:29 marco fos_linux[10679]:   File "/etc/fos/plugins/plugin-os-linux/linux_plugin", line 176, in __populate_node_information
feb 27 15:52:29 marco fos_linux[10679]:     node_info.update({'disks': self.get_disks_information()})
feb 27 15:52:29 marco fos_linux[10679]:   File "/etc/fos/plugins/plugin-os-linux/linux_plugin", line 657, in get_disks_information
feb 27 15:52:29 marco fos_linux[10679]:     mount)[0] / 1024 / 1024 / 1024  # conversion to gb
feb 27 15:52:29 marco fos_linux[10679]:   File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 1967, in disk_usage
feb 27 15:52:29 marco fos_linux[10679]:     return _psplatform.disk_usage(path)
feb 27 15:52:29 marco fos_linux[10679]:   File "/usr/lib/python3/dist-packages/psutil/_psposix.py", line 127, in disk_usage
feb 27 15:52:29 marco fos_linux[10679]:     st = os.statvfs(path)
feb 27 15:52:29 marco fos_linux[10679]: PermissionError: [Errno 13] Permission denied: '/media/marco/RED'
feb 27 15:52:29 marco fos_linux[10679]: Error in sys.excepthook:
feb 27 15:52:29 marco fos_linux[10679]: Traceback (most recent call last):
feb 27 15:52:29 marco fos_linux[10679]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 137, in apport_excepthook
feb 27 15:52:29 marco fos_linux[10679]:     os.unlink(pr_filename)
feb 27 15:52:29 marco fos_linux[10679]: PermissionError: [Errno 13] Permission denied: '/var/crash/_etc_fos_plugins_plugin-os-linux_linux_plugin.999.crash'
feb 27 15:52:29 marco fos_linux[10679]: Original exception was:
feb 27 15:52:29 marco fos_linux[10679]: Traceback (most recent call last):
feb 27 15:52:29 marco fos_linux[10679]:   File "/etc/fos/plugins/plugin-os-linux/linux_plugin", line 1007, in <module>
feb 27 15:52:29 marco fos_linux[10679]:     'uuid'), manifest)
feb 27 15:52:29 marco fos_linux[10679]:   File "/etc/fos/plugins/plugin-os-linux/linux_plugin", line 98, in __init__
feb 27 15:52:29 marco fos_linux[10679]:     self.__populate_node_information()
feb 27 15:52:29 marco fos_linux[10679]:   File "/etc/fos/plugins/plugin-os-linux/linux_plugin", line 176, in __populate_node_information
feb 27 15:52:29 marco fos_linux[10679]:     node_info.update({'disks': self.get_disks_information()})
feb 27 15:52:29 marco fos_linux[10679]:   File "/etc/fos/plugins/plugin-os-linux/linux_plugin", line 657, in get_disks_information
feb 27 15:52:29 marco fos_linux[10679]:     mount)[0] / 1024 / 1024 / 1024  # conversion to gb
feb 27 15:52:29 marco fos_linux[10679]:   File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 1967, in disk_usage
feb 27 15:52:29 marco fos_linux[10679]:     return _psplatform.disk_usage(path)
feb 27 15:52:29 marco fos_linux[10679]:   File "/usr/lib/python3/dist-packages/psutil/_psposix.py", line 127, in disk_usage
feb 27 15:52:29 marco fos_linux[10679]:     st = os.statvfs(path)
feb 27 15:52:29 marco fos_linux[10679]: PermissionError: [Errno 13] Permission denied: '/media/marco/RED'
feb 27 15:52:29 marco systemd[1]: fos_linux.service: Main process exited, code=exited, status=1/FAILURE
feb 27 15:52:29 marco systemd[1]: fos_linux.service: Failed with result 'exit-code'.
feb 27 15:52:30 marco systemd[1]: fos_linux.service: Service hold-off time over, scheduling restart.
feb 27 15:52:30 marco systemd[1]: fos_linux.service: Scheduled restart job, restart counter is at 5.
feb 27 15:52:30 marco systemd[1]: Stopped fos_linux.service.
feb 27 15:52:30 marco systemd[1]: fos_linux.service: Start request repeated too quickly.
feb 27 15:52:30 marco systemd[1]: fos_linux.service: Failed with result 'exit-code'.
feb 27 15:52:30 marco systemd[1]: Failed to start fos_linux.service.
```

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3 Tricia
 - Involved plugin: OS-Linux

**Comment by gabrik** [comment]
Hi @marcogozzi, #7 should have fix this, can you check?

**Comment by marcogozzi** [comment]
Hi @gabrik, now the plugin works correctly; every 5 seconds the service still tries to read the information from the disk failing so the journal is filled with the same error line

**Comment by gabrik** [comment]
@marcogozzi it is as expected, I just print out the error because of logging, it is not a big deal. 

If nothing crashes I will merge close this.
